name: SySE SA
favicon: null
layout_spectrum: 0.8611993209924549
typography_spectrum: 0.7234603832475841
title: Te conseguimos trabajo que más deseas para salir adelante.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#268294'
    - '#ffffff'
    - '#78d4e0'
    - '#aaaaaa'
    - '#00ffff'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
