name: SySE SA
favicon: null
layout_spectrum: 0.8611993209924549
typography_spectrum: 0.7234603832475841
title: Te conseguimos el mejor trabajo que más deseas para salir adelante.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8366188993677497
  lightness: 0.5558936237357557
  saturation: 0.06503937230445445
  rhythmicContrast: 0.5022616495843977
purpose: []
